'use client';

import React, { useEffect, useState, useRef } from 'react';
import Link from 'next/link';

interface Article {
  id: number;
  title: string;
  slug: string;
  theme: string;
  target_keywords: string;
  human_insert: string;
  content: string;
  meta_description: string;
  featured_image: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export default function DashboardBlogPage() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);
  
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [editingArticle, setEditingArticle] = useState<Partial<Article>>({});
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  // Image Upload Logic
  const [uploadedImages, setUploadedImages] = useState<string[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    fetchArticles();
  }, []);

  const fetchArticles = async () => {
    try {
      setLoading(true);
      const res = await fetch('/api/blog');
      if (res.status === 401) {
        setIsAuthenticated(false);
        setLoading(false);
        return;
      }
      setIsAuthenticated(true);
      const data = await res.json();
      setArticles(data.articles || []);
    } catch (err) {
      console.error(err);
    } finally {
      if (isAuthenticated !== false) setLoading(false);
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || e.target.files.length === 0) return;
    setIsUploading(true);
    
    try {
      const formData = new FormData();
      formData.append('file', e.target.files[0]);

      const res = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error);

      // Add to tracked list for AI generator
      setUploadedImages(prev => [...prev, data.filename]);
      
      // Auto-set as featured image if none exists
      if (!editingArticle.featured_image) {
        setEditingArticle(prev => ({ ...prev, featured_image: data.url }));
      }
      
      alert('Gambar berhasil diupload! AI akan melatakannya di dalam artikel.');
    } catch (err: any) {
      alert('Error upload: ' + err.message);
    } finally {
      setIsUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleGenerateAI = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch('/api/blog/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: editingArticle.title,
          theme: editingArticle.theme,
          human_insert: editingArticle.human_insert,
          uploaded_images: uploadedImages,
        })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);

      // Auto-fill all fields generated by AI
      setEditingArticle(prev => ({
        ...prev,
        content: data.content,
        meta_description: data.meta_description,
        slug: data.slug || prev.title?.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        target_keywords: data.target_keywords,
      }));
      
      alert('Artikel SEO beserta Keyword dan Slug berhasil digenerate AI!');
    } catch (err: any) {
      alert('Error generating: ' + err.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async (status: 'draft' | 'published') => {
    setIsSaving(true);
    try {
      const payload = { ...editingArticle, status };
      const method = payload.id ? 'PUT' : 'POST';
      
      const res = await fetch('/api/blog', {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      
      alert(`Article ${status === 'published' ? 'Published' : 'Saved'}!`);
      setView('list');
      fetchArticles();
      setUploadedImages([]); // reset
    } catch (err: any) {
      alert('Error saving: ' + err.message);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm('Hapus artikel ini?')) return;
    try {
      const res = await fetch(`/api/blog?id=${id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Gagal menghapus');
      fetchArticles();
    } catch (err: any) {
      alert(err.message);
    }
  };

  if (isAuthenticated === false) {
    return (
      <div className="h-screen bg-charcoal flex flex-col items-center justify-center p-6 text-white text-center">
        <h1 className="text-xl font-bold mb-2">Akses Ditolak</h1>
        <p className="text-sm text-text-muted mb-4">Anda harus login ke dashboard terlebih dahulu.</p>
        <Link href="/dashboard" className="bg-maroon px-6 py-2 rounded-lg text-sm font-bold">Ke Halaman Login</Link>
      </div>
    );
  }

  if (loading || isAuthenticated === null) {
    return <div className="h-screen bg-charcoal flex items-center justify-center text-text-muted animate-pulse">Loading Web Manager...</div>;
  }

  return (
    <div className="h-screen bg-charcoal text-text-light flex flex-col" style={{ fontFamily: 'var(--font-manrope)' }}>
      {/* Top Bar */}
      <header className="h-14 bg-charcoal-800 border-b border-border-industrial flex items-center justify-between px-6 shrink-0 relative z-10">
        <div className="flex items-center gap-4">
          <Link href="/dashboard" className="text-white/50 hover:text-white transition-colors text-sm">⬅ Kembali</Link>
          <h1 className="text-sm font-bold text-white tracking-tight">AI SEO Blog Manager</h1>
        </div>
        {view === 'list' && (
          <button 
            onClick={() => { setEditingArticle({}); setView('edit'); setUploadedImages([]); }}
            className="bg-maroon hover:bg-red-700 text-white text-xs font-bold px-4 py-2 rounded transition-colors"
          >
            + Tulis Artikel Baru
          </button>
        )}
      </header>

      <div className="flex-1 overflow-y-auto p-6 bg-charcoal-900/50">
        {view === 'list' ? (
          <div className="max-w-6xl mx-auto space-y-4">
            {articles.length === 0 ? (
              <div className="text-center py-20 text-text-muted border border-dashed border-border-industrial rounded-xl">
                Belum ada artikel. Klik "Tulis Artikel Baru" untuk mulai membuat konten dengan AI.
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {articles.map(art => (
                  <div key={art.id} className="bg-charcoal border border-border-industrial rounded-xl p-5 hover:border-amber/50 transition-all flex flex-col">
                    <div className="flex items-start justify-between mb-3">
                      <span className={`text-[10px] font-bold px-2 py-1 rounded uppercase tracking-wider ${art.status === 'published' ? 'bg-green-500/20 text-green-400' : 'bg-white/10 text-white/50'}`}>
                        {art.status}
                      </span>
                      <button onClick={() => handleDelete(art.id)} className="text-white/30 hover:text-red-400 text-xs">Hapus</button>
                    </div>
                    <h3 className="text-lg font-bold text-white mb-2 line-clamp-2">{art.title}</h3>
                    <p className="text-xs text-text-muted line-clamp-3 mb-4 flex-1">{art.meta_description || 'Tidak ada deskripsi'}</p>
                    <div className="flex gap-2 mt-auto">
                      <button 
                        onClick={() => { setEditingArticle(art); setView('edit'); setUploadedImages([]); }}
                        className="flex-1 bg-white/5 hover:bg-white/10 text-white text-xs font-bold py-2 rounded transition-colors"
                      >
                        Edit Artikel
                      </button>
                      {art.status === 'published' && (
                        <Link href={`/blog/${art.slug}`} target="_blank" className="bg-amber/10 hover:bg-amber/20 text-amber text-xs font-bold py-2 px-4 rounded transition-colors text-center">
                          Lihat
                        </Link>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : (
          <div className="max-w-4xl mx-auto bg-charcoal border border-border-industrial rounded-xl p-6 shadow-2xl space-y-8">
            <h2 className="text-xl font-bold text-white border-b border-border-industrial pb-4">
              {editingArticle.id ? 'Edit Artikel' : 'Draft Artikel AI Baru'}
            </h2>
            
            {/* STEP 1: Core Inputs */}
            <div className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">Judul Artikel Utama (H1)</label>
                <input type="text" value={editingArticle.title || ''} onChange={e => setEditingArticle({...editingArticle, title: e.target.value})} className="w-full bg-charcoal-800 border border-border-industrial rounded-lg px-4 py-3 text-sm text-white focus:outline-none focus:border-maroon" placeholder="Contoh: Jasa Laser Cutting Plat Besi Presisi Tinggi..." />
              </div>
              <div>
                <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">Topik/Fokus Pembahasan</label>
                <input type="text" value={editingArticle.theme || ''} onChange={e => setEditingArticle({...editingArticle, theme: e.target.value})} className="w-full bg-charcoal-800 border border-border-industrial rounded-lg px-4 py-3 text-sm text-white focus:outline-none focus:border-maroon" placeholder="Pentingnya detail dan presisi ketebalan plat 10mm" />
              </div>
            </div>

            {/* STEP 2: Media Upload */}
            <div className="bg-charcoal-800/30 border border-border-industrial rounded-xl p-5">
              <h3 className="text-sm font-bold text-white mb-2">📸 Tambahkan Gambar Penunjang (Opsional)</h3>
              <p className="text-xs text-text-muted mb-4">Upload gambar yang relevan. AI akan otomatis membuat tag <code>&lt;img&gt;</code> ke dalam artikel secara natural.</p>
              
              <div className="flex items-center gap-4">
                <input 
                  type="file" 
                  accept="image/*" 
                  ref={fileInputRef}
                  onChange={handleFileUpload} 
                  className="hidden" 
                />
                <button 
                  onClick={() => fileInputRef.current?.click()}
                  disabled={isUploading}
                  className="bg-charcoal-900 border border-border-industrial hover:border-amber hover:text-amber text-white text-xs font-bold px-4 py-2 rounded transition-colors flex items-center justify-center min-w-[120px]"
                >
                  {isUploading ? "Mengupload..." : "Upload Gambar Baru"}
                </button>
                
                {/* Uploaded List */}
                <div className="flex-1 flex flex-wrap gap-2">
                  {uploadedImages.map((img, i) => (
                    <span key={i} className="text-[10px] bg-amber/10 border border-amber/20 text-amber px-2 py-1 rounded-full flex items-center">
                      ✓ {img}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* STEP 3: Human Insert */}
            <div className="bg-emerald-900/10 border border-emerald-500/20 rounded-xl p-5">
              <h3 className="text-sm font-bold text-emerald-400 mb-2">🧑‍💻 Injeksi Teks Asli (Anti-AI Penalty)</h3>
              <p className="text-xs text-emerald-500/70 mb-4">Tulis satu atau dua paragraf kalimat jualan/insight asli Boss di sini. AI akan menenun kalimat ini ke dalam artikel tanpa mengubah satu katapun agar terasa 100% buatan manusia.</p>
              <textarea rows={4} value={editingArticle.human_insert || ''} onChange={e => setEditingArticle({...editingArticle, human_insert: e.target.value})} className="w-full bg-charcoal-900 border border-emerald-500/30 rounded-lg px-4 py-3 text-sm text-emerald-300 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/50" placeholder="Ketik kalimat original di sini..."></textarea>
            </div>

            {/* STEP 4: GENERATE BUTTON */}
            <div className="flex justify-center py-4">
              <button 
                onClick={handleGenerateAI}
                disabled={isGenerating || !editingArticle.title || !editingArticle.theme}
                className="bg-gradient-to-r from-amber to-amber-strong text-charcoal font-black px-8 py-4 rounded-xl shadow-xl hover:scale-105 transition-transform disabled:opacity-50 disabled:hover:scale-100 flex items-center gap-3 text-sm uppercase tracking-wider"
              >
                {isGenerating ? <div className="w-5 h-5 border-2 border-charcoal/30 border-t-charcoal rounded-full animate-spin" /> : "🤖 Generate Artikel & SEO JSON Sekarang"}
              </button>
            </div>

            {/* STEP 5: Review & Polish (Auto-filled by AI) */}
            <div className="pt-8 border-t border-dashed border-border-industrial space-y-6">
              <h3 className="text-lg font-bold text-white">Hasil Render Artikel (Auto-Generated)</h3>
              
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">URL Slug (Auto)</label>
                  <input type="text" value={editingArticle.slug || ''} onChange={e => setEditingArticle({...editingArticle, slug: e.target.value})} className="w-full bg-charcoal-900 border border-border-industrial rounded-lg px-4 py-2 text-sm text-text-muted focus:outline-none focus:border-amber" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">Target Keywords (Auto)</label>
                  <input type="text" value={editingArticle.target_keywords || ''} onChange={e => setEditingArticle({...editingArticle, target_keywords: e.target.value})} className="w-full bg-charcoal-900 border border-border-industrial rounded-lg px-4 py-2 text-sm text-text-muted focus:outline-none focus:border-amber" />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">Meta Description (Auto)</label>
                <textarea rows={2} value={editingArticle.meta_description || ''} onChange={e => setEditingArticle({...editingArticle, meta_description: e.target.value})} className="w-full bg-charcoal-900 border border-border-industrial rounded-lg px-4 py-2 text-sm text-text-muted focus:outline-none focus:border-amber"></textarea>
              </div>

              <div>
                <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">Konten HTML Lengkap</label>
                <textarea rows={24} value={editingArticle.content || ''} onChange={e => setEditingArticle({...editingArticle, content: e.target.value})} className="w-full bg-charcoal-900 border border-border-industrial rounded-lg px-4 py-4 text-sm text-white focus:outline-none focus:border-maroon font-mono leading-relaxed" placeholder="Hasil dari AI akan muncul di sini..."></textarea>
              </div>
              
              <div>
                <label className="block text-xs font-bold text-text-muted mb-2 uppercase tracking-wider">Gambar Utama (Thumbnail URL)</label>
                <input type="text" value={editingArticle.featured_image || ''} onChange={e => setEditingArticle({...editingArticle, featured_image: e.target.value})} className="w-full bg-charcoal-900 border border-border-industrial rounded-lg px-4 py-2 text-sm text-emerald-400 focus:outline-none focus:border-amber" />
                <p className="text-[10px] text-text-muted mt-1">Otomatis terisi jika Anda upload gambar di Editor Image atas.</p>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-between pt-6 border-t border-border-industrial mt-8">
              <button onClick={() => setView('list')} className="text-white/50 hover:text-white text-sm font-bold">Batal Kembali</button>
              <div className="flex gap-4">
                <button 
                  onClick={() => handleSave('draft')}
                  disabled={isSaving || !editingArticle.title}
                  className="bg-white/10 hover:bg-white/20 text-white font-bold px-6 py-3 rounded-xl text-sm transition-colors"
                >
                  Simpan ke Draft
                </button>
                <button 
                  onClick={() => handleSave('published')}
                  disabled={isSaving || !editingArticle.title || !editingArticle.content}
                  className="bg-green-600 hover:bg-green-500 text-white font-bold px-8 py-3 rounded-xl text-sm transition-colors disabled:opacity-50"
                >
                  Publish ke Website
                </button>
              </div>
            </div>

          </div>
        )}
      </div>
    </div>
  );
}
